Objects search
EnterpriseyIntranet/edap pull request #6
Opened 2019-04-08 00:00 UTC by danil-topc

Based on #5

2019-04-10 22:08 UTC, matejak requested changes
This change is good and useful, there are just minor string issues.
Could you rebase against the current master and also add unit tests for newly added functionality?

2019-04-10 22:08 UTC, matejak commented on src/edap/edap.py
> +        return self.get_users(search="uid={}".format(uid))
It is probably safer to use `f"uid={uid}"`

2019-04-13 18:27 UTC, danil-topc commented
Rebased, added tests and changed to f-strings.

2019-04-15 22:20 UTC, matejak approved these changes
Looks great, thanks!

2019-04-15 22:20 UTC, merged